version: '3'

services:
    mkdocs:
        container_name: mkdocs
        image: polinux/mkdocs:1.5.2
        restart: always
        ports:
            - "8000:8000"
        environment:
            LIVE_RELOAD_SUPPORT: 'true'
            ADD_MODULES: 'fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material mkdocs-video'
            FAST_MODE: 'true'
            DOCS_DIRECTORY: '/mkdocs'
        volumes:
            - .:/mkdocs
